import Link from 'next/link'
import React from 'react'
export const metadata = {
  title: 'Samples',
  description: 'Generated by create next app',
}
const getSamples = async () => {
  const res = await fetch(`${process.env.FETCH_URL}/samples`, {
    cache: 'force-cache',
  })
  const samples = await res.json()
  return samples
}
const Samples = async () => {
  const data = await getSamples()

  return (
    <div>
      <div>
        <strong>Total</strong> {data.length}
      </div>
      {data.map((item, index) => {
        return (
          <div key={index}>
            <h1>
              <strong>{item._id}</strong>
            </h1>
            <p>{item.name}</p>
            <Link href={`/samples/${item._id}`}>Read More</Link>
            <hr />
          </div>
        )
      })}
    </div>
  )
}

export default Samples
