import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// test

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
