import Footer from './components/footer/footer'
import Header from './components/header/header'
import './globals.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// test

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
